apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-keycodemon-org
spec:
  dnsNames:
    - "*.keycodemon.org"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: wildcard-keycodemon-org-tls-cert
