apiVersion: v1
kind: Service
metadata:
  name: evn-proxy
  namespace: evn-proxy
spec:
  type: NodePort
  selector:
    app: evn-proxy
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30082
